### ISSUE TITLE
bug if u have just one item on listView

### ISSUE THREAD

**Issue by rennanhm** [andersericsson/MultiColumnList#2]
If I have only one item on listView
when you click the item
the application crash 

 IndexOutOfBoundsException: Invalid index 0, size is 0
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
 at com.example.ColumnListView.isTopItemVisible(ColumnListView.java:615)
 at com.example.ColumnListView.removeNonVisibleViews(ColumnListView.java:604)
   at com.example.ColumnListView.scrollListTo(ColumnListView.java:586)
 at com.example.ColumnListView.access$1100(ColumnListView.java:24)
            at com.example.ColumnListView$FlingRunnable.run(ColumnListView.java:847)

**Comment by rennanhm** [comment]
its work with

private boolean isTopItemVisible(final Column column) {
        if(column.mItems.size()!=0){
           return column.mItems.get(0).mView.getBottom() >= 0;
        }
        return true;
    }

```
private boolean isBottomItemVisible(final Column column) {
    if(column.mItems.size()!=0){
        return column.mItems.get(column.mItems.size() - 1).mView.getTop() <= getHeight() - getPaddingBottom();
    }
    return true;
}
```
